application: django-kelp
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?tests/.*
- ^(.*/)?tests_coffee/.*
- ^(.*/)?tests_python/.*
- ^test\.py
- ^README\.md
- ^bower_components/.*
- ^package\.json
- ^node_modules/.*
- ^submodules/.*
- ^\.idea/.*
- ^_images/.*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.sass
- ^(.*/)?.*\.rb


handlers:
- url: /favicon\.ico
  static_files: application/static/icon/favicon.ico
  upload: application/static/icon/favicon\.ico
# font
- url: /font/
  static_dir: application/static/font
# images
- url: /image/
  static_dir: application/static/image
# CSS
- url: /css/
  static_dir: application/static/css
# JavaScript
- url: /javascript/
  static_dir: application/static/javascript
# Angular Templates
- url: /views/
  static_dir: application/templates_angular

- url: .*
  script: application.app
