application: django-kelp
version: 1
runtime: python27
api_version: 1
threadsafe: yes


skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?tests/.*
- ^README\.md
- ^\.gitignore
- ^\.gitmodules
- ^\.git/.*
- ^package\.json
- ^\node_modules/.*
- ^\.idea/.*
- ^_images/.*
- ^(.*/)?.*\.coffee
- ^(.*/)?.*\.scss
- ^(.*/)?.*\.sass
- ^(.*/)?.*\.rb


handlers:
- url: /favicon\.ico
  static_files: application/static/icon/favicon.ico
  upload: application/static/icon/favicon\.ico
# images
- url: /static/image/
  static_dir: application/static/image
# CSS
- url: /static/css/
  static_dir: application/static/css
# JavaScript
- url: /static/javascript/
  static_dir: application/static/javascript
# Angular Templates
- url: /views/
  static_dir: application/templates_angular

- url: .*
  script: application.app


libraries:
- name: django
  version: "1.5"
